stages:
  - build
  - test
  - deploy


variables:
  SCHEDULER_PARAMETERS: "-C haswell -M escori -q xfer -N1 -t 02:00:00"

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINESOURCE == "push"'
      when: always

dev-build:
  stage: build
  only: 
    - dev
  tags: [cori]
  script:
    - bash conda/build-nersc.sh w_2022_10

dev-test:
  stage: test
  only:
    - dev
  tags: [cori]
  script: 
    - bash conda/test-nersc.sh 

dev-deploy:
  stage: deploy
  only:
    - dev
  tags: [cori]
  script:
    - bash conda/build-nersc.sh w_2022_10 1
    - bash conda/set-symlinks.sh dev
    

main-build:
  stage: build
  only: 
    - main
  tags: [cori]
  script:
    - bash conda/build-nersc.sh w_2022_10 1

main-test:
  stage: test
  only:
    - main
  tags: [cori]
  script: 
    - bash conda/test-nersc.sh 1

main-deploy:
  stage: deploy
  only:
    - main
  tags: [cori]
  script:
    - bash conda/set-symlinks.sh stable




