stages:
  - build
  - test
  - deploy


variables:
  SCHEDULER_PARAMETERS: "-C haswell -M escori -q xfer -N1 -t 02:00:00"

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "trigger" && $CI_COMMIT_TAG'
    - if: '$CI_PIPELINE_SOURCE == "web" || $CI_PIPELINE_SOURCE == "schedule" || $CI_PIPELINE_SOURCE == "push"'
      when: always

dev-build:
  stage: build
  only: 
    - dev
  tags: [cori]
  script:
    - bash conda/build-nersc.sh w_2022_10

dev-test:
  stage: test
  only:
    - dev
  tags: [cori]
  script: 
    - bash conda/test-nersc.sh 

dev-deploy:
  stage: deploy
  only:
    - dev
  tags: [cori]
  script:
    - bash conda/build-nersc.sh w_2022_10
    - bash conda/set-symlinks.sh dev
    
    
release-build:
  stage: build
  rules: 
    - if: '$CI_COMMIT_TAG'
  tags: [cori]
  script:
    - bash conda/build-nersc.sh w_2022_10 1

release-test:
  stage: test
  rules: 
    - if: '$CI_COMMIT_TAG'
  tags: [cori]
  script: 
    - bash conda/test-nersc.sh 1

release-deploy:
  stage: deploy
  rules: 
    - if: '$CI_COMMIT_TAG'
  tags: [cori]
  script:
    - bash conda/set-symlinks.sh stable-test    
    
    
    
main-build:
  stage: build
  only: 
    - main
  except: 
    - if: '$CI_COMMIT_TAG'
  tags: [cori]
  script:
    - bash conda/build-nersc.sh w_2022_10 1

main-test:
  stage: test
  only:
    - main
  except: 
    - if: '$CI_COMMIT_TAG'
  tags: [cori]
  script: 
    - bash conda/test-nersc.sh 1

main-deploy:
  stage: deploy
  only:
    - main
  except: 
    - if: '$CI_COMMIT_TAG'
  tags: [cori]
  script:
    - bash conda/set-symlinks.sh prod
    




