name: base
channels:
  - conda-forge/label/mpi-external
  - conda-forge
dependencies:
  - python=3.12
  - conda[version='>=25.3.0']
  - mamba[version='>=2.1.1']
  - astroplan
  - astropy
  - camb
  - celerite
  - cmdstan
  - cmdstanpy
  - coloredlogs
  - compilers
  - cosmosis
  - cosmosis-build-standard-library
  - diffsky
  - dust_extinction
  - dustmaps
  - emcee
  - f90nml
  - firecrown
  - george
  - gwpy
  - ipdb
  - jax
  - jaxlib
  - lalsuite
  - lenstronomy
  - lightcurvelynx
  - ligo.skymap
  - ligo.em-bright
  - lsdb
  - lsstdesc-gcr-catalogs
  - mpi4py
  - mpich
  - opencosmo
  - polars
  - pycryptodome
  - pyqt
  - root_base
  - sacc
  - seaborn
  - sncosmo
  - tensorflow-cpu
  - xgboost
  - yaml
  - pip:
    - chainconsumer
    - eazy
    - lsstdesc-dataregistry
    - git+https://github.com/MickaelRigault/skysurvey
