name: td_env docker integration

on: 
  push:
    branches:
      - integration
  workflow_dispatch:

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - name: Check Disk Space
      run: df -h && sudo apt-get clean && df -h 
    - name: Docker login
      run: echo '${{ secrets.DOCKERHUB_ACCESSTOK }}' | docker login --username heather999 --password-stdin
    - name : Docker prune
      run: sudo docker system prune && df -h 
    - name: checkout td_env
      uses: actions/checkout@v2
      with:
         fetch-depth: 0
         ref: integration
    - name : Get weekly number and date 
      run: |
        echo "LSST_TAG=w_2022_10" >> $GITHUB_ENV
        echo "DATE_TAG=$(date "+%F")" >> $GITHUB_ENV         
    - name: update docker image
      run: |
        cd $GITHUB_WORKSPACE 
        docker run -u root -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE --name="install-int-mpich" lsstsqre/centos:7-stack-lsst_distrib-w_2022_10 /bin/bash /$GITHUB_WORKSPACE/docker/install-mpich.sh
        docker commit -m"initial testing" install-int-mpich lsstdesc/td-integration:mpich
        docker run -u lsst -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE -w $GITHUB_WORKSPACE/conda --name="td-int-test-env" lsstdesc/td-integration:mpich /bin/bash /$GITHUB_WORKSPACE/docker/update-docker.sh ${{env.LSST_TAG}}
        docker commit -m"initial testing" td-int-test-env lsstdesc/td-integration:test
        docker rmi -f lsstdesc/td-integration:mpich
        docker run -u lsst -w /opt/lsst/software/stack --name="td-int-setwd" lsstdesc/td-integration:test /bin/bash
        docker commit -m"initial testing" td-int-setwd lsstdesc/td-env:${{env.LSST_TAG}}-${{env.DATE_TAG}}-integration
        docker rmi -f lsstdesc/td-integration:test
    - name: Test and push
      run: |
        docker run --rm lsstdesc/td-env:${{env.LSST_TAG}}-${{env.DATE_TAG}}-integration /bin/bash -c "source /opt/lsst/software/stack/loadLSST.bash && setup lsst_distrib && python -c 'import coloredlogs'"
        docker push lsstdesc/td-env:${{env.LSST_TAG}}-${{env.DATE_TAG}}-integration
        docker tag lsstdesc/td-env:${{env.LSST_TAG}}-${{env.DATE_TAG}}-integration lsstdesc/td-env:integration
        docker push lsstdesc/td-env:integration
#        mkdir -p /tmp/desc
#        docker save lsstdesc/td-env:integration > /tmp/desc/lsstdesc-td-env-integration.tar
#    - name: Upload docker tarball
#      uses: actions/upload-artifact@v3
#      with:
#          name: lsstdesc-td-env-integration
#          path: /tmp/desc/lsstdesc-td-env-integration.tar
