name: td_env gpu docker dev

on: 
 # push:
 #   branches:
 #     - dev
  workflow_dispatch:

env:
  TEST_TAG: lsstdesc/td-env-gpu:test-dev

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-22.04
    steps:
    # https://github.com/jlumbroso/free-disk-space/issues/14
    - name: Update Package List and Remove Dotnet
      run: |
        sudo apt-get update
        sudo apt-get remove -y '^dotnet-.*'
  
    - name: pull old build
      run: |
        docker pull lsstdesc/td-env-gpu:dev
        docker tag lsstdesc/td-env-gpu:dev lsstdesc/td-env-gpu:old
        docker push lsstdesc/td-env-gpu:old
        
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        # this might remove tools that are actually needed,
        # if set to "true" but frees about 6 GB
        tool-cache: false    
        # all of these default to true, but feel free to set to
        # "false" if necessary for your workflow
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Check Disk Space
     # run: df -h && sudo apt-get clean && df -h 
      run: df -h    
    - name: Docker login
      run: echo '${{ secrets.DOCKERHUB_ACCESSTOK }}' | docker login --username heather999 --password-stdin
    #- name : Docker prune
    #  run: sudo docker system prune --all --force && df -h 
    - name: checkout td_env
      uses: actions/checkout@v4
      with:
         fetch-depth: 0
         ref: dev
    - name : Get weekly number and date 
      run: |
        echo "DATE_TAG=$(date "+%F")" >> $GITHUB_ENV         
    - name: update docker image
      run: |
        cd $GITHUB_WORKSPACE 
        ls $GITHUB_WORKSPACE
        echo $GITHUB_WORKSPACE
        ls $GITHUB_WORKSPACE/conda
  
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
  #    with: 
  #      driver: docker 
        
    - name: Build 
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true
        tags: ${{ env.TEST_TAG }}
 #       build-args: |
 #         GH_SHA=${{ github.sha }}
     
   
    - name: test image before pushing
      run: |
        docker run --rm ${{ env.TEST_TAG }} /bin/bash -c "source /opt/desc/py/etc/profile.d/conda.sh && conda activate base && python -c 'import coloredlogs'"
        docker tag ${{ env.TEST_TAG }} lsstdesc/td-env-gpu:dev-${{env.DATE_TAG}}
        docker push lsstdesc/td-env-gpu:dev-${{env.DATE_TAG}}
        docker tag ${{ env.TEST_TAG }} lsstdesc/td-env-gpu:dev
        docker push lsstdesc/td-env-gpu:dev
      
