name: td_env gitlab release
# Mirror when there is a release tag
on: 
 release:
  types: [published]
  
jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - name: Trigger gitlab build
      run: |
        curl -X POST \
        --fail \
        -F token={{ secrets.GITLAB_TRIGGER_TOKEN }} \
        -F "ref=main" \
        -F "variables[TD_ENV_TAG]=${{ github.event.release.tag_name }}" \
        https://software.nersc.gov/api/v4/projects/402/trigger/pipeline
 
